config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier
  validates :name, :height, :width, :depth, :weight, :sku, :supplier_id, presence: true
  validates :sku, uniqueness: true
  validates :weight, :height, :depth, :width, numericality: { greater_than: 0 }
  validates :sku, length: {is: 20, wrong_length: "deve ter 20 caracteres"}
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :corporate_name, :brand_name, :registration_number, :email, presence: true
  validates :registration_number, uniqueness: true
  validates :registration_number, length: {is: 13, wrong_length: "deve ter 13 caracteres"}
  validates :registration_number, numericality: {only_integer: true, message: "deve conter apenas números"}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  validates :name, :code, :city, :description, :address, :cep, :area, presence: true
  validates :code, :name, uniqueness: true
  validates :cep, format: { with: /\A[0-9]{5}-[0-9]{3}\z/,
                            message: "deve ter o formato 00000-000" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @warehouses = Warehouse.all
  end
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  
  def index
    @product_models = ProductModel.all
  end

  def new
    @product_model = ProductModel.new
    @suppliers = Supplier.all
  end

  def create
    product_model_params = params.require(:product_model).permit(:name, :height, :width, :depth,
                                                                 :weight, :sku, :supplier_id)
    @product_model = ProductModel.new(product_model_params)
    if @product_model.save
      redirect_to @product_model, notice: 'Modelo de produto cadastrado com sucesso'
    else
      @suppliers = Supplier.all
      flash.now[:notice] = 'Não foi possível cadastrar o modelo de produto.'
      render 'new'
    end
  end

  def show
    @product_model = ProductModel.find(params[:id])
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: [:show, :edit, :update]

  def index
    @suppliers = Supplier.all
  end

  def show; end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)                                                      
    if @supplier.save()
      redirect_to suppliers_path, notice: 'Fornecedor cadastrado com sucesso.'
    else
      flash.now[:notice] = 'Fornecedor não cadastrado.'
      render 'new'
    end
  end

  def edit; end

  def update
    if @supplier.update(supplier_params)
      redirect_to supplier_path(@supplier.id), notice: 'Fornecedor Atualizado com sucesso.'
    else
      flash.now[:notice] = 'Não foi possivel atualizar o fornecedor.'
      render 'edit'
    end
  end

  private

  def supplier_params
    supplier_params = params.require(:supplier).permit(:corporate_name, :brand_name, :registration_number, 
                                                      :full_address, :city, :state, :email, :phone_number)
  end

  def set_supplier
    @supplier = Supplier.find(params[:id])
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :set_warehouse, only: [:show, :edit, :update, :destroy]

  def show; end

  def new
    @warehouse = Warehouse.new
  end

  def create
    @warehouse = Warehouse.new(warehouse_params)
    if @warehouse.save()
      redirect_to root_path, notice: 'Galpão cadastrado com sucesso.'
    else
      flash.now[:notice] = 'Galpão não cadastrado.'
      render 'new'
    end
  end

  def edit; end

  def update
    if @warehouse.update(warehouse_params)
      redirect_to warehouse_path(@warehouse.id), notice: 'Galpão Atualizado com sucesso'
    else
      flash.now[:notice] = 'Não foi possivel atualizar o galpão.'
      render 'edit'
    end
  end

  def destroy
    @warehouse.destroy
    redirect_to root_path, notice: 'Galpão removido com sucesso'
  end

  private

  def set_warehouse
    @warehouse = Warehouse.find(params[:id])
  end

  def warehouse_params
    params.require(:warehouse).permit(:name, :code, :city, :description, :address,
                                      :cep, :area)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb

<section id="warehouses">
  <h2>Galpões</h2>

  <div>
    <%= link_to('Cadastrar Galpão', new_warehouse_path) %>
  </div>

  <% @warehouses.each do |w| %>
    <div>
      <h3><%= link_to(w.name, warehouse_path(w.id)) %></h3>
      <dl>
        <dt>Código:</dt>
        <dd><%= w.code %></dd>

        <dt>Cidade:</dt>
        <dd><%= w.city %></dd>

        <dt>Área:</dt>
        <dd><%= w.area %> m²</dd>
      </dl>
    </div>
  <% end %>

  <% if @warehouses.empty? %>
    <p>Não existem galpões cadastrados</p>
  <% end%>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>

    <header>
      <h1>Sistema de Galpões e Estoque</h1>
    </header>

    <main>
      <nav>
        <%= link_to 'Tela Inicial', root_path %> |
        <%= link_to 'Fornecedores', suppliers_path %> |
        <%= link_to 'Modelos de Produtos', product_models_path %> |
        <% if user_signed_in? %>
          <%= current_user.email %> |
          <%= button_to 'Sair', destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to 'Entrar', new_user_session_path %>
        <% end %>
      </nav>
      <div>
        <%= flash[:alert] %>
        <%= flash[:notice] %>
      </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/product_models/index.html.erb
<h1>Modelos de Produtos</h1>

<%= link_to 'Cadastrar Novo', new_product_model_path %>
<% if @product_models.any? %>

  <% @product_models.each do |pm| %>
    <div>
      <h2><%= pm.name %></h2>
      <dl>
        <dt>SKU</dt>
        <dd><%= pm.sku %></dd>
        <dt>Fornecedor</dt>
        <dd><%= pm.supplier.brand_name %></dd>
      </dl>
    </div>
  <% end %>

<% else %>
  <p>Nenhum modelo de produto cadastrado.
<% end %>

app/views/product_models/new.html.erb
<h1>Cadastrar Novo Modelo de Produto</h1>

<% if(@product_model.errors.any?) %>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @product_model.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @product_model) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :weight %>
    <%= f.number_field :weight %>
  </div>
  <div>
    <%= f.label :height %>
    <%= f.number_field :height %>
  </div>
  <div>
    <%= f.label :width %>
    <%= f.number_field :width %>
  </div>
  <div>
    <%= f.label :depth %>
    <%= f.number_field :depth %>
  </div>
  <div>
    <%= f.label :sku %>
    <%= f.text_field :sku %>
  </div>
  <div>
    <%= f.label :supplier_id %>
    <%= f.collection_select :supplier_id, @suppliers, :id, :brand_name %>
  </div>
  <%= f.submit 'Enviar' %>  
<% end %>

app/views/product_models/show.html.erb
<h1><%= @product_model.name %></h1>
<dl>
  <dt>Fornecedor:</dt>
  <dd><%= @product_model.supplier.brand_name %></dd>
  <dt>SKU:</dt>
  <dd><%= @product_model.sku %></dd>
  <dt>Dimensão:</dt>
  <dd><%= @product_model.height %>cm x <%= @product_model.width %>cm x <%= @product_model.depth %>cm</dd>
  <dt>Peso:</dt>
  <dd><%= @product_model.weight %>g</dd>
</dl>

app/views/suppliers/_form.html.erb
<% if(@supplier.errors.any?) %>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @supplier.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @supplier) do |s| %>
  <div>
    <%= s.label :corporate_name %>
    <%= s.text_field :corporate_name %>
  </div>
  
  <div>
    <%= s.label :brand_name %>
    <%= s.text_field :brand_name %>
  </div>
  
  <div>
    <%= s.label :registration_number %>
    <%= s.text_field :registration_number %>
  </div>
  
  <div>
    <%= s.label :full_address %>
    <%= s.text_field :full_address %>
  </div>
  
  <div>
    <%= s.label :city %>
    <%= s.text_field :city %>
  </div>
  
  <div>
    <%= s.label :state %>
    <%= s.text_field :state %>
  </div>
  
  <div>
    <%= s.label :email %>
    <%= s.text_field :email %>
  </div>
  
  <div>
    <%= s.label :phone_number %>
    <%= s.text_field :phone_number %>
  </div>

  <div>
    <%= s.submit 'Enviar' %>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<h1>Editar Fornecedor</h1>

<%= render 'form' %>

app/views/suppliers/index.html.erb
<h1>Fornecedores</h1>

<% if @suppliers.any? %>
  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Localização</th>
      </tr>
    </thead>
    <tbody>
      <% @suppliers.each do |s| %>
      <tr>
        <td><%= link_to s.brand_name, s %></td>
        <td><%= s.city %> - <%= s.state %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else%>
  <p>Não existem fornecedores cadastrados.</p>
<% end %>

<%= link_to 'Cadastrar novo fornecedor', new_supplier_path %>

app/views/suppliers/new.html.erb
<h1>Novo fornecedor</h1>

<%= render 'form' %>

app/views/suppliers/show.html.erb
<h1>Fornecedor <%= @supplier.brand_name %></h1>
<h2><%= @supplier.corporate_name %></h2>

<dl>
  <dt>Documento:</dt>
  <dd><%= @supplier.registration_number%></dd>
  <dt>Endereço:</dt>
  <dd><%= @supplier.full_address %> - <%= @supplier.city %> - <%= @supplier.state %></dd>
  <dt>E-mail:</dt>
  <dd><%= @supplier.email%></dd>
  <dt>Telefone:</dt>
  <dd><%= @supplier.phone_number%></dd>
</dl>

<%= link_to 'Editar', edit_supplier_path(@supplier) %>

app/views/warehouses/_form.html.erb
<% if(@warehouse.errors.any?) %>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @warehouse.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @warehouse) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>
  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :cep %>
    <%= f.text_field :cep %>
  </div>
  <div>
    <%= f.label :area %>
    <%= f.number_field :area %>
  </div>

  <div>
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/warehouses/edit.html.erb
<h1>Editar Galpão</h1>

<%= render 'form' %>

app/views/warehouses/new.html.erb
<h1>Novo Galpão</h1>

<%= render 'form' %>

app/views/warehouses/show.html.erb
<h1>Galpão <%= @warehouse.code %></h1>
<h2><%= @warehouse.description %></h2>
<div>
  <strong>Nome: </strong><%= @warehouse.name %>
  <strong>Cidade: </strong><%= @warehouse.city %>
  <strong>Área: </strong><%= @warehouse.area %> m²
  <strong>Endereço: </strong><%= @warehouse.address %> <strong>CEP: </strong> <%= @warehouse.cep %>
</div>

<div>
  <%= button_to 'Remover', warehouse_path(@warehouse.id), method: :delete %>
  <%= link_to 'Editar', edit_warehouse_path(@warehouse.id) %>
</div>